### ISSUE TITLE
I can't find the pixi-blit.js or the /dist folder where it should be in

### ISSUE THREAD

**Issue by TimHaerkens** [gameofbombs/pixi-blit#1]
Like the title mentions, I can't find the file to use this plugin.
Has the folder /dist been removed? Or do I have to import it in a different way?

Also, the package.json says the repo url is https://github.com/pixijs/pixi-blit.git but it is https://github.com/gameofbombs/pixi-blit.git

Thanks in advance

**Comment by ivanpopelyshev** [comment]
Right, I didnt put it to pixi group 

eh, there's no `dist`, i didnt put binaries here, you have to build it. just `yarn build` or `npm run build` should work.

As for how to use , there's `examples` : https://github.com/gameofbombs/pixi-blit/tree/master/examples , you can set up node server (`http-server -c-1`) in root of repo and then open html files. 

The plugin is seriously under-documented. Basically, it automatically caches shapes in atlases, drawing in 2d, webgl or webgl2, and frees those that weren't used for some time. Its supposed to be a huge help for people who wants antialiasing on shapes.

**Comment by TimHaerkens** [comment]
Thanks for the reply. I managed to make a build.
I will try to fool around with it a bit.

**Comment by ivanpopelyshev** [comment]
You can ask anything here if you have concrete questions :)
